version: 1

formatters:
  default:
    format: "%(asctime)s %(levelname)s %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  root:
    level: DEBUG
    propagate: True
    handlers: [ console ]
